// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountDelete: typeof import('./components/account/AccountDelete.vue')['default']
    AccountFeedback: typeof import('./components/account/AccountFeedback.vue')['default']
    AccountOrganizations: typeof import('./components/account/AccountOrganizations.vue')['default']
    AccountOrganizationSummary: typeof import('./components/organizations/AccountOrganizationSummary.vue')['default']
    AccountProfile: typeof import('./components/account/AccountProfile.vue')['default']
    'AccountProfile copy': typeof import('./components/account/AccountProfile copy.vue')['default']
    AccountSettings: typeof import('./components/account/AccountSettings.vue')['default']
    BasicFooter: typeof import('./components/layouts/BasicFooter.vue')['default']
    BasicNavBar: typeof import('./components/layouts/BasicNavBar.vue')['default']
    copy: typeof import('./components/account/AccountProfile copy.vue')['default']
    CustomerRecord: typeof import('./components/account/CustomerRecord.vue')['default']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElMain: typeof import('element-plus/es')['ElMain']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarAccount: typeof import('./components/layouts/SidebarAccount.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
    WorkshopCard: typeof import('./components/workshops/WorkshopCard.vue')['default']
  }
}
