// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    2: typeof import('./components/account/AccountProfile copy 2.vue')['default']
    AccountDelete: typeof import('./components/account/AccountDelete.vue')['default']
    AccountFeedback: typeof import('./components/account/AccountFeedback.vue')['default']
    AccountOrganizations: typeof import('./components/account/AccountOrganizations.vue')['default']
    AccountOrganizationSummary: typeof import('./components/organizations/AccountOrganizationSummary.vue')['default']
    AccountProfile: typeof import('./components/account/AccountProfile.vue')['default']
    'AccountProfile copy 2': typeof import('./components/account/AccountProfile copy 2.vue')['default']
    AccountSettings: typeof import('./components/account/AccountSettings.vue')['default']
    BasicFooter: typeof import('./components/layouts/BasicFooter.vue')['default']
    BasicNavBar: typeof import('./components/layouts/BasicNavBar.vue')['default']
    CustomerRecord: typeof import('./components/account/CustomerRecord.vue')['default']
<<<<<<< HEAD
    ElContainer: typeof import('element-plus/es')['ElContainer']
=======
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
>>>>>>> master
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElMain: typeof import('element-plus/es')['ElMain']
<<<<<<<

=======
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
<<<<<<< HEAD
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
>>>>>>>
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
=======
    HelloWorld: typeof import('./components/testing/HelloWorld.vue')['default']
>>>>>>> master
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarAccount: typeof import('./components/layouts/SidebarAccount.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
    WorkshopCard: typeof import('./components/workshops/WorkshopCard.vue')['default']
  }
}
